# Generated by Django 4.2.3 on 2023-07-21 10:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.CharField(blank=True, help_text='Latitude value in decimal degrees e.g. 39.362483', max_length=10, null=True, verbose_name='Latitude')),
                ('longitude', models.CharField(blank=True, help_text='Longitude value in decimal degrees e.g. 22.940186', max_length=10, null=True, verbose_name='Longitude')),
                ('country', models.CharField(blank=True, help_text='Automatically derived from latitude and longitude', max_length=100, null=True, verbose_name='Country')),
                ('city', models.CharField(blank=True, help_text='Automatically derived from latitude and longitude', max_length=100, null=True, verbose_name='City')),
                ('units', models.BooleanField(default=True, help_text='If set to false, imperial units will be used', verbose_name='Metric units')),
                ('open_weather_api_key', models.CharField(blank=True, max_length=500, null=True, verbose_name='Open weather API key')),
            ],
            options={
                'verbose_name_plural': 'Settings',
            },
        ),
    ]
