# Generated by Django 4.2.3 on 2023-07-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='timezone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Automatically derived from latitude and longitude'),
        ),
    ]
