# Generated by Django 4.2.3 on 2023-07-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_setting_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='timezone',
            field=models.CharField(blank=True, help_text='Automatically derived from latitude and longitude', max_length=100, null=True, verbose_name='Timezone'),
        ),
    ]
