# Generated by Django 4.2.3 on 2023-07-21 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_rename_units_setting_metric_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='latitude',
            field=models.CharField(default='', help_text='Latitude value in decimal degrees e.g. 39.362483', max_length=10, verbose_name='Latitude'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='setting',
            name='longitude',
            field=models.CharField(default='', help_text='Longitude value in decimal degrees e.g. 22.940186', max_length=10, verbose_name='Longitude'),
            preserve_default=False,
        ),
    ]
