# Generated by Django 4.2.3 on 2023-07-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_alter_setting_latitude_alter_setting_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='open_weather_api_key',
            field=models.CharField(default='', max_length=500, verbose_name='Open weather API key'),
            preserve_default=False,
        ),
    ]
