# Generated by Django 4.2.3 on 2023-10-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_alter_setting_open_weather_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='bookmark_category_group_size',
            field=models.PositiveIntegerField(blank=True, default=6, help_text="The number of categories to group together in the UI. For example, if you set this to 6 and there are 12 categories, they will be displayed as 2 groups of 6 categories each. Leave this field blank if you don't want any grouping.", null=True),
        ),
    ]
