# Generated by Django 4.2.3 on 2023-10-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_setting_bookmark_category_group_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='bookmark_category_group_size',
            field=models.PositiveIntegerField(blank=True, default=6, help_text="The number of categories to group together in the UI. For example, if you set this to 6 and there are 12 categories, they will be displayed as 2 groups of 6 categories each. Set to zero or leave this field blank if you don't want any grouping.", null=True, verbose_name='Bookmark categories group size'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='latitude',
            field=models.CharField(blank=True, help_text='Latitude value in decimal degrees e.g. 39.362483', max_length=10, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='longitude',
            field=models.CharField(blank=True, help_text='Longitude value in decimal degrees e.g. 22.940186', max_length=10, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='open_weather_api_key',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Open weather API key'),
        ),
    ]
