# Generated by Django 4.2.3 on 2023-11-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0009_alter_setting_metric_units'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='metric_units',
        ),
        migrations.AddField(
            model_name='setting',
            name='system_of_measurement',
            field=models.CharField(choices=[('metric', 'Metric'), ('imperial', 'Imperial'), ('standard', 'Standard')], default='metric', help_text='<strong>Metric:</strong>\nTemperature Symbol: °C\nTemperature Unit: Celsius\nSpeed: m/s\nHumidity: %\nPressure: hPa\nVisibility: m\n\n\n\n<strong>Imperial:</strong>\nTemperature Symbol: °F\nTemperature Unit: Fahrenheit\nSpeed: mph\nHumidity: %\nPressure: hPa\nVisibility: m\n\n\n\n<strong>Standard:</strong>\nTemperature Symbol: K\nTemperature Unit: Kelvin\nSpeed: m/s\nHumidity: %\nPressure: hPa\nVisibility: m', max_length=10, verbose_name='System of measurement'),
        ),
    ]
