# Generated by Django 4.2.3 on 2023-11-03 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0010_remove_setting_metric_units_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='forecast_type',
            field=models.CharField(choices=[('hourly', 'Hourly'), ('weekly', 'Weekly')], default='hourly', help_text='The default type of weather forecast data to be displayed.', max_length=6, verbose_name='Forecast type'),
        ),
    ]
