# Generated by Django 4.2.3 on 2023-11-09 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0011_setting_forecast_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='forecast_type',
            field=models.CharField(choices=[('hourly', 'Hourly'), ('weekly', 'Weekly')], default='weekly', help_text='The default type of weather forecast data to be displayed.', max_length=6, verbose_name='Forecast type'),
        ),
    ]
