# Generated by Django 4.2.3 on 2023-11-18 16:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0013_setting_weather_data_last_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='weather_data_refresh_interval',
        ),
        migrations.AddField(
            model_name='setting',
            name='weather_data_update_interval',
            field=models.PositiveSmallIntegerField(blank=True, default=60, help_text='The duration (in minutes) that must elapse before the weather data can be manually or automatically updated again.', null=True, validators=[django.core.validators.MinValueValidator(limit_value=10), django.core.validators.MaxValueValidator(limit_value=1440)], verbose_name='Weather data refresh interval (minutes)'),
        ),
    ]
