# Generated by Django 4.2.3 on 2023-07-19 17:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookmarkCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='Category', help_text='The bookmark category name (50 characters max).', max_length=50, null=True, verbose_name='Name')),
                ('color', models.CharField(blank=True, default='#000', help_text='The hex color value should be a maximum of 9 characters, including the # symbol.', max_length=9, null=True, verbose_name='Color')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Date updated')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='Bookmark', help_text='50 characters max.', max_length=50, null=True, verbose_name='Name')),
                ('url', models.URLField(help_text='1000 characters max.', max_length=1000, verbose_name='Bookmark URL')),
                ('icon_url', models.URLField(help_text='1000 characters max.', max_length=1000, verbose_name='Icon URL')),
                ('is_shortcut', models.BooleanField(default=False, help_text='The bookmark will be displayed in the shortcuts sidebar.', verbose_name='Is shortcut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Date updated')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookmarks.bookmarkcategory', verbose_name='Bookmark Category')),
            ],
            options={
                'verbose_name_plural': 'Bookmarks',
            },
        ),
    ]
