# Generated by Django 4.2.3 on 2023-11-19 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0005_bookmark_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookmarks.bookmarksubcategory', verbose_name='Bookmark Sub Category'),
        ),
    ]
