# Generated by Django 4.2.3 on 2023-07-24 17:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchEngine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Search engine name e.g. Google', max_length=50, unique=True, verbose_name='Name')),
                ('url', models.URLField(help_text='The url of the search engine plus the value of the action attribute of the form e.g. https://www.google.com<b>/search</b>', max_length=1000, unique=True, verbose_name='Action URL')),
                ('method', models.CharField(help_text='The value of the form method e.g. GET', max_length=50, verbose_name='Form method')),
                ('name_attribute', models.CharField(help_text='The value of the name attribute of the type=search element e.g. q', max_length=50, verbose_name='Name attribute')),
            ],
            options={
                'verbose_name_plural': 'Search Engines',
            },
        ),
    ]
