# Generated by Django 4.2.3 on 2023-07-25 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchengine',
            name='is_default',
            field=models.BooleanField(default=False, help_text='This search engine will be used as the default. Only one search engine can be set as the default', verbose_name='Is Default'),
        ),
    ]
