# Generated by Django 4.2.3 on 2023-09-15 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engines', '0003_alter_searchengine_options_alter_searchengine_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchengine',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
