# Generated by Django 4.2.3 on 2023-11-19 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('search_engines', '0004_searchengine_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchengine',
            name='user',
            field=models.ForeignKey(default='a0568738-0f3a-43cc-bf69-48e264e35fb5', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
            preserve_default=False,
        ),
    ]
