# Generated by Django 4.2.3 on 2023-11-21 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='Profile image URL'),
        ),
    ]
